[advisories]
ignore = [
    "RUSTSEC-2023-0071", # RSA Marvin Attack - via sqlx-mysql which we don't directly use
    "RUSTSEC-2024-0375", # atty unmaintained warning
    "RUSTSEC-2024-0388", # derivative unmaintained warning 
    "RUSTSEC-2021-0141", # dotenv unmaintained warning
    "RUSTSEC-2024-0436", # paste unmaintained warning
    "RUSTSEC-2024-0370", # proc-macro-error unmaintained warning
    "RUSTSEC-2021-0145", # atty potential unaligned read warning
]
