[print_schema]
file = "src/schema.rs"
import_types = ["diesel::sql_types::*"]
generate_missing_sql_type_definitions = true

[migrations_directory]
dir = "migrations"

[treat_none_as_default_value]
sqlite = false
postgres = true
mysql = false
