version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: explorer
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    environment:
      - SOURCE_DB_URL=postgresql://username:password@hostname:port/database?sslmode=require
      - DEST_DB_URL=postgres://postgres:postgres@db:5432/explorer
      - PORT=${PORT}
    restart: always

volumes:
  db_data:
