name: 🚀 Test SSH & Deploy Script Access (Dev)

on:
  workflow_dispatch:

env:
  APP_NAME: penumbra-explorer
  SERVER_USER: deploy-penumbra-explorer
  SERVER_HOST: ${{ secrets.SERVER_HOST_DEV }}

jobs:
  test-deploy-access:
    name: Test SSH & Script Execution
    runs-on: ubuntu-latest
    steps:
      - name: 🔑 Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_SSH_KEY_DEV }}
          known_hosts: unnecessary

      - name: 📡 Add Dev Server to known_hosts
        run: ssh-keyscan -H ${{ env.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: 🚀 Run deploy.sh (expecting failure is OK)
        run: |
          echo "Trying to SSH and run the deploy script..."
          ssh ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} '/opt/deployment/deploy.sh || echo "✅ Reached server and tried to run deploy.sh (fail expected)"'
