name: Test SCP Transfer

on:
  workflow_dispatch:

env:
  SERVER_USER: deploy-penumbra-explorer-stage
  SERVER_HOST: ${{ secrets.SERVER_HOST_STAGE }}

jobs:
  test-transfer:
    name: Test File Transfer
    runs-on: ubuntu-latest
    steps:
      - name: Create test file
        run: echo "Test file content" > /tmp/test-file.txt

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_SSH_KEY_STAGE }}
          known_hosts: unnecessary

      - name: Add server to known hosts
        run: ssh-keyscan -H ${{ env.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Transfer test file
        run: scp /tmp/test-file.txt "${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:~/deployments/"