name: Blue-Green Deploy to Hetzner

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  APP_NAME: penumbra-explorer
  SERVER_USER: deploy
  SERVER_HOST: ${{ secrets.SERVER_HOST }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ${{ env.APP_NAME }}:latest
          outputs: type=docker,dest=/tmp/${{ env.APP_NAME }}.tar

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          known_hosts: unnecessary

      - name: Add server to known hosts
        run: ssh-keyscan -H ${{ env.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Transfer Docker image
        run: |
          scp /tmp/${{ env.APP_NAME }}.tar ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:~/deployments/

      - name: Deploy with Blue-Green mechanism
        run: |
          ssh ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} 'sudo /opt/deployment/deploy.sh'

      - name: Check deployment status
        run: |
          ssh ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} 'cat /opt/deployment/deploy.log | tail -20'
